### ISSUE TITLE
按钮设计有问题

### ISSUE THREAD

**Issue by rainssong** [fairygui/FairyGUI-starling#5]
通常按钮按下后，如果想Cancel，可以通过拖曳出按钮区域取消这次点击。而Demo中无此功能

修改建议：
按钮侦测MouseOut和MouseOver事件，触发MouseOut后取消按下状态，若再触发MouseOver恢复按下状态。

**Comment by fairygui** [comment]
此问题早已解决，请下载新的demo或者pull最新的代码。
